### PR TITLE
add mkdocs documentation skeleton

### PR DESCRIPTION
**Pull request by jothepro**
Preview: https://jothepro.github.io/djinni-documentation/djinni-support-lib/install/

This is part of the global documentation. The resulting website will look like this: https://jothepro.github.io/djinni-documentation

`djinni-documentation` will include `djinni-support-lib` as a submodule. All `support-lib` related information can be documented here inside the docs folder. 

See https://github.com/cross-language-cpp/djinni-documentation/pull/3 for more details about the new documentation structure.

### CODE REVIEW

**Review by a4z — APPROVED** [review]
awesome, thank you !

**Comment by a4z** [comment]
The only question I have is, why is the mkdocs.yml in this (sub) project so much more than in other (sub) projects ?

**Comment by jothepro** [comment]
Umph, that's the wrong yaml. Thx!

**Comment by a4z** [comment]
Thanks for the fast update!

**Pull request merged**
