### PR TITLE
fix: CsOptional partial specialization for array

### PR DESCRIPTION
**Pull request by FanglinIfolor**
Fix wrong matched template for `array<T>^`

This commit fixes the wrong deduced type for `CsOptional<array<T>^>`, which should be matched to `CsOptional<T^>`, but matched to `CsOptional<T>`. Same for `IsRef`.

### CODE REVIEW

**Comment by a4z** [comment]
the PR looks fine, but it seems something changes at the github action Windows images, maybe a different VS Studio per default .
Guess that's a potential problem when running gh actiosn on *-latest images

See 
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#visual-studio-enterprise-2022

@FanglinIfolor , can you please update this line in your PR 
https://github.com/cross-language-cpp/djinni-support-lib/blob/549752ff2f7ae3287825ac398cb7c0c58c2c6597/.github/workflows/build.yml#L128

and replace here
`windows-latest` with  `windows-2019`



--

We can also the copy the whole block and make it work for windows-latest buy updating this 
https://github.com/cross-language-cpp/djinni-support-lib/blob/549752ff2f7ae3287825ac398cb7c0c58c2c6597/.github/workflows/build.yml#L139

I guess `-G "Visual Studio 16 2019"` needs to be replaced with `-G "Visual Studio 17 2022"` to see if it works on `windows-latest` also, which is `windows-2022`

but we do not need to do that in the context of this PR

**Comment by FanglinIfolor** [comment]
@a4z Thanks for another quick review :) Changed it to VS 2022. Could you approve running workflows? Thank you.

**Review by a4z — APPROVED** [review]
even without being a C# expert I think I can say this is a good change

Thanks a lot!

**Comment by FanglinIfolor** [comment]
Close accidentally, reopen, sorry for inconvenience...

**Review by freitass — APPROVED** [review]
Great catch! Since we don't have an `optional<array>` on our codebase I never came across this problem. Thanks for submitting this fix!

**Comment by jothepro** [comment]
> First three work with the original implementation but not for data4: optional<binary>.

I guess that's because array is a "primitive" language feature while `list`, etc. are class types? Do you agree with that theory?

**Comment by FanglinIfolor** [comment]
> I guess that's because array is a "primitive" language feature while `list`, etc. are class types? Do you agree with that theory?

I really have no clue 😵 🏳️. I did a simple test as following to see which template specialization is matched:

```cpp
/** test.cpp **/

template<class T>
void foo(T value) {
    System::Console::WriteLine("Function: T");
};

template<class T>
void foo(T^ value) {
    System::Console::WriteLine("Function: T^");
};

//template<class T>
//void foo(array<T>^ value) {
//    System::Console::WriteLine("Function: array<T>^");
//};

// =================

template<class T>
struct Bar {
    static void print() {
        System::Console::WriteLine("Class: T");
    }
};

template<class T>
struct Bar<T^> {
    static void print() {
        System::Console::WriteLine("Class: T^");
    }
};

//template<class T>
//struct Bar<array<T>^> {
//    static void print() {
//        System::Console::WriteLine("Class: array<T>^");
//    }
//};

ref class Baz {};

int main()
{
    int i = 10;
    foo(i);

    int^ handle_i = gcnew int(10);
    foo(handle_i);

    Baz^ handle_baz = gcnew Baz;
    foo(handle_baz);

    array<int>^ array_int = gcnew array<int> {1, 2, 3, 4, 5};
    foo(array_int);

    array<System::Byte>^ array_byte = gcnew array<System::Byte> {1, 2, 3, 4, 5};
    foo(array_byte);

    array<Baz^>^ array_baz = gcnew array<Baz^>(3);
    foo(array_baz);

    Bar<int>::print();
    Bar<int^>::print();
    Bar<Baz^>::print();
    Bar<typename array<int>^>::print();
    Bar<typename array<float>^>::print();
    Bar<typename array<Baz^>^>::print();
}
```
(`cl /clr test.cpp && .\test.exe` to compile and execute the binary)

Outputs:
```
Function: T
Function: T^
Function: T^
Function: T^
Function: T^
Function: T^
Class: T
Class: T^
Class: T^
Class: T
Class: T
Class: T
```

The behavior is different for function template specialization and for struct template specialization. If we uncomment the specialization for `array<T>^`, last three of `foo(...)` and `Bar<...>` would be matched correctly to the specialization for  `array<T>^`.

**Comment by a4z** [comment]
Can we merge that PR? 

I think we agree it looks fine, or? 
The last discussion is only for interest and to explore a topic, or is it an issue?

Merging would also enable auto CI runs for @FanglinIfolor , since that makes him to a contributor, 
and for the PRs that are coming to the generator there will no extra confirmation be required

**Review by jothepro — APPROVED** [review]

**Comment by a4z** [comment]
done, I hope you like how I squashed the PR, if not, I am sorry for making it not look as nice as it should

**Comment by FanglinIfolor** [comment]
Looks great! Thank you guys so much for the detailed review and awesome discussions :)

**Pull request merged**
