### PR TITLE
update referenced djinni-generator version

### PR DESCRIPTION
**Pull request by jothepro**

### CODE REVIEW

**Review by a4z — APPROVED** [review]
Thank you! 

I have of course to wonder if we want to keep that file in the project

**Comment by jothepro** [comment]
Is there a change that I forgot about that makes the generator version definition in this file obsolete? 😮

**Comment by a4z** [comment]
not obsolete, but using asdf is a personal choice , and it's a point of possible failure.
I can have the latest version in path, with asdf installed and global set to system, when I get this file, I have the version in the file. that might be wanted or not ... depends, mostly it is, except when it isn't ....

**Comment by a4z** [comment]
now I remember that we use the file in CI to get the right version ...

**Comment by jothepro** [comment]
That's why I was confused about your proposal to remove it. 👍

**Pull request merged**
