### PR TITLE
updated hardcoded version references to the latest release

### PR DESCRIPTION
**Pull request by jothepro**

### CODE REVIEW

**Review by a4z — APPROVED** [review]
Thanks you!

**Comment by a4z** [comment]
about the conan version, we could apply ranges as I mentioned for the support lib
for the git_tag, maybe we should introduce a `latest` tag that moves with the current release?
this could be set by the CI, then we can have a more generic description that does not need extra steps

**Comment by jothepro** [comment]
Hmm... Setting a latest tag sounds like a dangerous thing to me, bc one would loose control over which version is referenced by the tag.

**Comment by a4z** [comment]
> Hmm... Setting a latest tag sounds like a dangerous thing to me, bc one would loose control over which version is referenced by the tag.

we would of course add that info into the docs, that it's recommended using an explicit version tag

And for people that do copy and past without reading and understanding what they put in they project, maybe deserve an exiting life if the right thing for them ;-)

**Pull request merged**
